import type { Metadata } from "next";

// Fonts
import { Geist, Geist_Mono } from "next/font/google";

// styles
import "@/styles/globals.css";

// Providers
import { Provider } from "@/providers/session-providers";

// Components
import { RightBar } from "@/components/molecules/right-bar";
import { LeftBar } from "@/components/molecules/left-bar";
import { Sidebar } from "@/components/organisms/sidebar";


const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">

			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Provider>
					<div className="lg:grid lg:grid-cols-8">
						<LeftBar />
						<div className="col-span-6 px-4 md:px-0">
							<Sidebar useRemoteWork />
							<div className="py-6 md:px-6 md:py-4">{children}</div>
						</div>
						<RightBar />
					</div>
				</Provider>
			</body>
		</html>
	);
}
