import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/globals.css";
import "@blocknote/mantine/style.css";
import { Provider } from "@/providers/session-providers";
import DashboardSidebar from "@/components/organisms/dashboard-sidebar";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="dark">

			<body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
				<Provider>
					<div className="h-screen w-screen overflow-hidden flex flex-row">
						<DashboardSidebar />
						<div className="flex flex-col flex-1">
							<div className="flex-1 p-4 min-h-0 overflow-auto">
							<ToastContainer closeButton={true} position="top-right" />
								{children}
							</div>
						</div>
					</div>
				</Provider>
			</body>
		</html>
	);
}
